[build]
  command = """
  set -eo pipefail
  rm -rf package-lock.json node_modules/\\@ndn
  npm install
  npm run lint && [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
  npm run build
  """
  publish = "public/"
