[build]
  command = """
  set -euo pipefail
  corepack pnpm install
  corepack pnpm build-trust-policy
  corepack pnpm build
  corepack pnpm lint && git diff --exit-code
  rm -rf pnpm-lock.yaml node_modules
  """
  publish = "public/"

[build.environment]
  NODE_VERSION="26"
  NPM_FLAGS="--version"
