[build]
  command = """
  set -eo pipefail
  corepack pnpm install
  corepack pnpm build-trust-policy
  corepack pnpm build
  corepack pnpm lint && git diff --exit-code
  """
  publish = "public/"

[build.environment]
  NODE_VERSION="17"
  NPM_FLAGS="--version"
