[build]
  command = """
  set -euo pipefail
  rm -rf node_modules/@ndn node_modules/.pnpm/@ndn*
  corepack pnpm install
  corepack pnpm build-trust-policy
  corepack pnpm build
  corepack pnpm lint && git diff --exit-code
  """
  publish = "public/"

[build.environment]
  NODE_VERSION="22"
  NPM_FLAGS="--version"
